### PR TITLE
Johnmoehrke build for r4

### LINKED ISSUE #45: Rebuild as R4 IG rather than R4B
R4B was used as R4B includes a technical correction in Consent resource that fixes a profiling error. However, it is clear now that R4B is not the version of FHIR that is being published (evidence gathered on the DSUB for Mobile). 

R4B does have [significant changes](http://hl7.org/fhir/R4B/r4b-explanation.html) in for example the medications, clinical reasoning, and subscriptions; but R4B was also intended to be the technical-correction minor correction on R4 for fixes like that done for Consent. Unfortunately, because of the significant changes, the R4B release can't be seen purely as a minor technical-correction release of R4.

The current release does include statements that it is compatible with R4 and does have both R4 and R4B packages. However, the experience we have with DSUB for Mobile shows that one can't depend on an R4B IG and further refine (profile) the source profiles. Thus, keeping PCF at R4B will limit the kind of refinements.

Should the PCF be republished as an R4?
Should we do like the Subscription backport and create two different publications?

Building PCF as R4 will produce errors on each example
> if identifier.system is 'urn:ietf:rfc:3986', then the identifier.value must be a full URI (e.g. start with a scheme), not 'Local eCMS identifier'

This does not affect the profile, and doesn't really affect the example. It would however need to be explained to our reader that it is understood and okay.

Building PCF as R4 also requires narrative references to R4B to be changed to R4.

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #45

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
https://build.fhir.org/ig/IHE/ITI.PCF/branches/johnmoehrke-build-for-R4/index.html

**Comment by JohnMoehrke** [comment]
note that the download page does have the evaluation of no problems using this with R4B
image

**Review by lukeaduncan — APPROVED** [review]
Looks good.

**Comment by JohnMoehrke** [comment]
I think we just submitted the same change to ch-P.md

**Comment by JohnMoehrke** [comment]
yes. No harm. I just wanted to confirm that your change was the same.. The github DIFF is not really clear.

**Comment by lukeaduncan** [comment]
I only changed 2 links for security-labels.html and 1 for molecularsequence.html on line 492 in ch-P.
________________________________

**Comment by JohnMoehrke** [comment]
okay. I think it is okay now, rigth?

**Comment by lukeaduncan** [comment]
Looks good to me.
________________________________

**Pull request merged**
